Feature/what4 updates
Copilot-Language/copilot pull request #63
Opened 2020-11-09 19:53 UTC by benjaminselfridge

This adds examples related to the what4 functionality that will be merged into copilot-theorem.

This PR should not be merged until AFTER that merge occurs, so that we can bump the copilot-theorem submodule here.

2020-12-12 14:53 UTC, fdedden commented on Examples/what4/Structs.hs
> +                   , flag     :: Field "flag" Bool
What is the purpose of `flag`?

2020-12-12 14:55 UTC, fdedden commented on Examples/what4/Structs.hs
> +                       , other :: Field "other" (Array 10 (Array 5 Word32))
What does the `other` field do? Is it just there to add nesting to the example? If so, we might be able to come up with something nicer: in the end it is an example, and should be understandable by Copilot users.

2020-12-12 14:58 UTC, fdedden commented on Examples/what4/Structs.hs
> +    (((battery # volts) .!! 0) # numVolts) == (((battery # volts) .!! 0) # numVolts)
Is there a possibility this could fail in case of an incorrect what4-backend implementation? I think this property is always trivial by equality at the Haskell level.

2020-12-12 14:59 UTC, fdedden commented on copilot.cabal
> +                      , copilot     >= 3.1  && < 3.2
These versions are currently incorrect, as Copilot 3.2 (a very minor release) has been released very recently. I have already fixed them on my end.

2020-12-12 15:00 UTC, fdedden commented on copilot.cabal
>                        , copilot     >= 3.1  && < 3.2
These versions are currently incorrect, as Copilot 3.2 (a very minor release) has been released very recently. I have already fixed them on my end.

2020-12-12 15:02 UTC, fdedden requested changes
I have left some comments, especially in the structs example. Could you take a look at them? I can do any changes to the code.

2020-12-12 15:02 UTC, fdedden commented on copilot.cabal
>                        , copilot-libraries >= 3.1  && < 3.2
These versions are currently incorrect, as Copilot 3.2 (a very minor release) has been released very recently. I have already fixed them on my end.

2020-12-12 15:06 UTC, fdedden requested changes

2020-12-12 15:06 UTC, fdedden commented on Examples/what4/Structs.hs
> +                   , flag     :: Field "flag" Bool
What is the purpose of `flag`?

2020-12-12 15:06 UTC, fdedden commented on Examples/what4/Structs.hs
> +                       , other :: Field "other" (Array 10 (Array 5 Word32))
What does the other field do? Is it just there to add nesting to the example? If so, we might be able to come up with something nicer: in the end it is an example, and should be understandable by Copilot users.

2020-12-12 15:06 UTC, fdedden commented on Examples/what4/Structs.hs
> +    (((battery # volts) .!! 0) # numVolts) == (((battery # volts) .!! 0) # numVolts)
Is there a possibility this could fail in case of an incorrect what4-backend implementation? I think this property is always trivial by equality at the Haskell level.

2020-12-12 15:07 UTC, fdedden commented
Sorry for the mess regarding the review, apparently I can add comments that are part of the review, and comments that aren't. I have added the important ones to review.

2021-01-12 17:39 UTC, benjaminselfridge commented on Examples/what4/Structs.hs
> +                   , flag     :: Field "flag" Bool
There isn't a purpose; it's just there to give the struct more than one field.

2021-01-12 17:42 UTC, benjaminselfridge commented on Examples/what4/Structs.hs
> +                       , other :: Field "other" (Array 10 (Array 5 Word32))
Yep -- I didn't think too hard about what the example might "mean," I just wanted to illustrate that using nested structs and arrays works correctly. Let me know if you have any ideas of how I could modify this example or come up with something better -- otherwise, I'll try to think of a more natural use for nested arrays myself.

Another thing I could do would be to just take away the name `Battery` entirely and name these things `StructA`, `StructB`, etc., to indicate to the reader that they don't reflect any use in particular, but are merely examples to illustrate these language features.

2021-01-12 17:47 UTC, benjaminselfridge commented on Examples/what4/Structs.hs
> +    (((battery # volts) .!! 0) # numVolts) == (((battery # volts) .!! 0) # numVolts)
True, it is always trivial by equality -- in this case, that was the point, to show that something trivially true is indeed trivially true, in particular when array/struct indexing are used. For the solver, this property boils down to checking that an uninterpreted constant is equally to itself, which is certainly trivially true. Do you need me to think of more interesting things to prove? (I don't think there's anything super interesting to prove here that specifically relates to structs and arrays, but I could try to think of something.)

2021-01-25 18:53 UTC, fdedden approved these changes

2021-01-25 18:59 UTC, fdedden approved these changes
I have denied the changes to .gitmodules.

2021-01-25 18:59 UTC, fdedden commented on .gitmodules
> +	url = https://github.com/benjaminselfridge/copilot-language.git
I will be denying this commit; the submodules should always point to the ones from Copilot-Language, and not a fork of any of these repos. If changes need to be made to copilot-language, please create a pullrequest.

2021-01-25 19:03 UTC, merged